# Generated by Django 5.2.8 on 2025-11-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='studentsNew',
        ),
    ]
