# Generated by Django 5.2.8 on 2025-11-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_students_studentsnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsnew',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
